Store-Acquisition-Assistant\Store-Acquisition-Assistant\MainPage.xaml.cs(71,47,71,83): error CS0012: The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'
what a great way to tell me that the minimum version isn't high enough or whatever...